// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimesheetTracker.API.Data;

#nullable disable

namespace TimesheetTracker.API.Migrations
{
    [DbContext(typeof(TimesheetDbContext))]
    [Migration("20250731062502_SeedNewRolesUsers")]
    partial class SeedNewRolesUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TimesheetTracker.API.Models.Holiday", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Holidays");
                });

            modelBuilder.Entity("TimesheetTracker.API.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ClientName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77b82e92-ffa1-45ce-a820-9206711f27f5"),
                            Budget = 10000m,
                            ClientName = "Internal",
                            CreatedAt = new DateTime(2025, 7, 31, 6, 25, 2, 170, DateTimeKind.Utc).AddTicks(4749),
                            CreatedBy = new Guid("6299a0b7-e6cd-453d-bb48-246439c40724"),
                            Description = "This is a sample project for demonstration purposes",
                            EndDate = new DateTime(2025, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Sample Project",
                            StartDate = new DateTime(2025, 7, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 7, 31, 6, 25, 2, 170, DateTimeKind.Utc).AddTicks(4750)
                        });
                });

            modelBuilder.Entity("TimesheetTracker.API.Models.ShiftInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssignedToUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<Guid>("ShiftTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("ShiftTemplateId");

                    b.ToTable("ShiftInstances");
                });

            modelBuilder.Entity("TimesheetTracker.API.Models.ShiftTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecurrenceRule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("ShiftTemplates");
                });

            modelBuilder.Entity("TimesheetTracker.API.Models.TimeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("IX_TimeEntries_ProjectId");

                    b.HasIndex("UserId", "StartTime")
                        .HasDatabaseName("IX_TimeEntries_UserId_StartTime");

                    b.ToTable("TimeEntries");
                });

            modelBuilder.Entity("TimesheetTracker.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6299a0b7-e6cd-453d-bb48-246439c40724"),
                            CreatedAt = new DateTime(2025, 7, 31, 6, 25, 1, 759, DateTimeKind.Utc).AddTicks(7564),
                            Department = "",
                            Email = "admin@timesheettracker.com",
                            FirstName = "System",
                            IsActive = true,
                            LastName = "Administrator",
                            PasswordHash = "$2a$11$8kRzDIB59NsDcefeKFTWauMvKDv29YzrHd8YtNbhx3kDf8zuBUnjC",
                            Role = "Admin",
                            UpdatedAt = new DateTime(2025, 7, 31, 6, 25, 1, 759, DateTimeKind.Utc).AddTicks(7573)
                        },
                        new
                        {
                            Id = new Guid("8a59ff26-bd9a-4c83-bfc2-92f8dd10a311"),
                            CreatedAt = new DateTime(2025, 7, 31, 6, 25, 1, 896, DateTimeKind.Utc).AddTicks(5283),
                            Department = "",
                            Email = "teamlead@timesheettracker.com",
                            FirstName = "Team",
                            IsActive = true,
                            LastName = "Lead",
                            PasswordHash = "$2a$11$3CNzJp6.sNApHT4Vpw8h1eTyB/C8baWggxCDj7BPUKDTgUyXyuMIS",
                            Role = "TeamLead",
                            UpdatedAt = new DateTime(2025, 7, 31, 6, 25, 1, 896, DateTimeKind.Utc).AddTicks(5289)
                        },
                        new
                        {
                            Id = new Guid("4171f0df-44bb-44af-835e-dc6916616b39"),
                            CreatedAt = new DateTime(2025, 7, 31, 6, 25, 2, 34, DateTimeKind.Utc).AddTicks(5966),
                            Department = "",
                            Email = "manager@timesheettracker.com",
                            FirstName = "Project",
                            IsActive = true,
                            LastName = "Manager",
                            PasswordHash = "$2a$11$wS56TV8bJY89A6h4V9qXEekkMmTBHmtAusqc.og.KkWMyDwRIkm/e",
                            Role = "Manager",
                            UpdatedAt = new DateTime(2025, 7, 31, 6, 25, 2, 34, DateTimeKind.Utc).AddTicks(5972)
                        },
                        new
                        {
                            Id = new Guid("dbf0c851-44e1-409b-87aa-9fd84ca064b0"),
                            CreatedAt = new DateTime(2025, 7, 31, 6, 25, 2, 170, DateTimeKind.Utc).AddTicks(3974),
                            Department = "",
                            Email = "financehr@timesheettracker.com",
                            FirstName = "Finance",
                            IsActive = true,
                            LastName = "HR",
                            PasswordHash = "$2a$11$tdYdg0pFBDcxrjuwPerViOKLyNnGC6MTGLAyGCXTN7gqebxCBTP1q",
                            Role = "FinanceHR",
                            UpdatedAt = new DateTime(2025, 7, 31, 6, 25, 2, 170, DateTimeKind.Utc).AddTicks(3979)
                        });
                });

            modelBuilder.Entity("TimesheetTracker.API.Models.Project", b =>
                {
                    b.HasOne("TimesheetTracker.API.Models.User", "Creator")
                        .WithMany("Projects")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("TimesheetTracker.API.Models.ShiftInstance", b =>
                {
                    b.HasOne("TimesheetTracker.API.Models.ShiftTemplate", null)
                        .WithMany("Instances")
                        .HasForeignKey("ShiftTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TimesheetTracker.API.Models.TimeEntry", b =>
                {
                    b.HasOne("TimesheetTracker.API.Models.User", "Approver")
                        .WithMany("ApprovedTimeEntries")
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TimesheetTracker.API.Models.Project", "Project")
                        .WithMany("TimeEntries")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimesheetTracker.API.Models.User", "User")
                        .WithMany("TimeEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimesheetTracker.API.Models.Project", b =>
                {
                    b.Navigation("TimeEntries");
                });

            modelBuilder.Entity("TimesheetTracker.API.Models.ShiftTemplate", b =>
                {
                    b.Navigation("Instances");
                });

            modelBuilder.Entity("TimesheetTracker.API.Models.User", b =>
                {
                    b.Navigation("ApprovedTimeEntries");

                    b.Navigation("Projects");

                    b.Navigation("TimeEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
